# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7i_LXab6R_vtHCuPeYYRCGEhS_ZDoBo
"""



"""# Personal Health Dashboard: Step Tracker
This project analyzes my physical activity over one week. It calculates my total performance and shows a visual trend of my steps.
"""

import matplotlib.pyplot as plt

# 1. Our Data (Steps walked from Monday to Sunday)
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
steps = [4500, 7800, 5200, 9100, 6000, 12000, 8500]

# 2. The Math (Calculations)
total_steps = sum(steps)
average_steps = total_steps / len(steps)
best_day_value = max(steps)

# 3. Display the Results
print(f"Total Steps this week: {total_steps:,}")
print(f"Average Steps per day: {int(average_steps):,}")
print(f"Highest Step Count: {best_day_value:,}")

# 4. The Visual (Creating a Line Graph)
plt.figure(figsize=(8, 4))
plt.plot(days, steps, marker='o', color='green', linestyle='-')
plt.title("Weekly Step Trend")
plt.ylabel("Number of Steps")
plt.grid(True, linestyle='--', alpha=1)
plt.show()

"""# Project Summary:

**Through this Jupyter Notebook, We have demonstrated:**

1.   How to use **Markdown** for documentation
2.   How to use **Python** for data calculation.
3. How to use **Matplotlib** to visualize results directly in the browser.


"""

